project_id = "huydudorftiektexxpei"
[functions.createRequestWithInvoice]
verify_jwt = false
[functions.stripePayments]
enabled = true
verify_jwt = true
import_map = "./functions/stripePayments/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripePayments/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripePayments/*.html" ]

[functions.hello]
enabled = true
verify_jwt = true
import_map = "./functions/hello/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello/*.html" ]

[functions.stripeWebhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripeWebhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripeWebhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripeWebhook/*.html" ]

[functions.stripeRefund]
enabled = true
verify_jwt = true
import_map = "./functions/stripeRefund/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripeRefund/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripeRefund/*.html" ]

[functions.sendAdminPaymentEmail]
enabled = true
verify_jwt = true
import_map = "./functions/sendAdminPaymentEmail/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sendAdminPaymentEmail/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sendAdminPaymentEmail/*.html" ]
