invoice:
  terms_and_conditions: |
    Terms:
    Payment of this invoice constitutes acceptance of all terms and conditions listed herein.
    
    Payment Terms: All events must be paid in full prior to confirming the team.
    
    Payment Policies: All credit card payments incur a 3.5% transaction fee, check payments must be received 10 days before the event date.
    
    Last Minute Booking Fees: Any events booked less than 1 day before the start time, will incur a 20% surcharge.
    
    Standard cancelation: 50% refund if canceled 6 days prior to the event and 75% refund if canceled 30 days prior to the event.
    
    Extra time: To prevent any miscommunication for billable hours please confirm with your Account Manager before asking our team to stay longer than what's scheduled.
    
    Parking: Clients agree to reimburse all parking costs incurred by the team if parking is not provided and no street parking is available.
    
    Breaks: All team members are legally required to receive a 30 minute break on shifts of 6 hours or longer.
    
    Non-Solicitation Policy: Client agrees not to directly hire or contract Elevate Events staff without written approval from Elevate and payment of a staff buyout fee equal to 50% of the employee's projected annual earnings.
    
    Indemnification: Both parties agree to indemnify and hold each other harmless against any losses arising from gross negligence, misconduct, or breach of contractual obligations by their respective teams, as well as any workplace incidents or unauthorized use of deliverables resulting from their own negligence.